### ISSUE TITLE
Calendar color problems

### ISSUE THREAD

**Issue by JcM-productions** [gbl08ma/utilities#12]
1. Events over more than on month aren't colored in the next months - I think that arises by just loading all data from the actually month. So would it be possible to color the no-event-starting-month too?

2. The calendar category 0 isn't really visible (at the selected day) by using PrintXY because of the light grey.

3. The gray at the week view (category 0) is the same as the font color (and dark green is, concerning to gray, too dark - better: light green).

**Comment by gbl08ma** [comment]
Point 1 is not going to be implemented because it would require checking all previous months back to the lowest supported year (0) in search of events, which as you might guess, takes a completely unpractical amount of time; other option would be to have a central list of events that span over multiple months, but this list could get very large as people add events (thus checking it would take much time too), not to mention the additional code necessary to keep the list in sync with the other contents of the calendar database.

About point 2, category 0 is meant exactly to be almost invisible. Hence why it's category *zero*. All other possible colors for use with PrintXY are available as categories, and I think the almost-white grey used by category zero is not really a planned OS color, but more of a (useful) bug in the PrintXY function.

Point 3 will be taken care of soon.
