### ISSUE TITLE
Calculator lock function

### ISSUE THREAD

**Issue by JcM-productions** [gbl08ma/utilities#24]
The owner information at the new calculator lock screen doesn't function really with dark theme. (The background of the information is still white)

Problem: An "Flashing pop-up" chronometer notification lets press the MENU key successfully and you can go to Main Menu (I think this problem was there many versions ago --> maybe: why not make a "Note on home" while locking if the "Flashing pop-up" chronometer notification is active)

I liked the old lock screen more --> would it be possible to set up which screen should appear?

*Turning off at home screen broke (maybe) some prizms --> is this this case too (now)?*

**Comment by gbl08ma** [comment]
The issues you reported have been fixed.

A comeback of the old lock screen is not planned. The reason for this is that it would increase the code size for little benefit - most people I know were quite confused by the old lock screen and found it useless and not very clear (the letters were hard to see), while I remember having at least one person ask if it would be possible to show the clock on the lock screen.

Still up for consideration is the possibility of allowing a different type of clock on the lock screen than the one on the home screen. This would let you select the "blank clock" as the clock for the lock screen, effectively rendering an effect similar to the previous lock screen.

About your concerns regarding breaking calculators - I don't think the issue will repeat itself. If a problem even existed, it was due to the PowerOff syscall being called twice in a row in some occasions. The possibility of that occurrence has been eliminated some versions of Utilities ago, and there was never any certainty on whether it was really possible to brick Prizms by powering them off on the Utilities lock screen. It is far more likely that problems such as this one: http://www.cemetech.net/forum/viewtopic.php?p=234487#234487 were the actual cause of the majority of the bricks.
